version: '3'
services:
  app:
    container_name: test-app
    image: test-app
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/test_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_app
